/* soapC2BPaymentValidationAndConfirmationBindingProxy.h
   Generated by gSOAP 2.8.60 for mpesab2b.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapC2BPaymentValidationAndConfirmationBindingProxy_H
#define soapC2BPaymentValidationAndConfirmationBindingProxy_H
#include "soapH.h"

    class SOAP_CMAC C2BPaymentValidationAndConfirmationBindingProxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        bool soap_own; ///< flag indicating that this context is owned by this proxy when context is shared
        /// Endpoint URL of service 'C2BPaymentValidationAndConfirmationBindingProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in mpesab2b.h, if any
        /// Construct a proxy with new managing context
        C2BPaymentValidationAndConfirmationBindingProxy();
        /// Copy constructor
        C2BPaymentValidationAndConfirmationBindingProxy(const C2BPaymentValidationAndConfirmationBindingProxy& rhs);
        /// Construct proxy given a shared managing context
        C2BPaymentValidationAndConfirmationBindingProxy(struct soap*);
        /// Constructor taking an endpoint URL
        C2BPaymentValidationAndConfirmationBindingProxy(const char *endpoint);
        /// Constructor taking input and output mode flags for the new managing context
        C2BPaymentValidationAndConfirmationBindingProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        C2BPaymentValidationAndConfirmationBindingProxy(const char *endpoint, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        C2BPaymentValidationAndConfirmationBindingProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes non-shared managing context only (use destroy() to delete deserialized data)
        virtual ~C2BPaymentValidationAndConfirmationBindingProxy();
        /// Initializer used by constructors
        virtual void C2BPaymentValidationAndConfirmationBindingProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual C2BPaymentValidationAndConfirmationBindingProxy *copy();
        /// Copy assignment
        C2BPaymentValidationAndConfirmationBindingProxy& operator=(const C2BPaymentValidationAndConfirmationBindingProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault string (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail as string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Web service operation 'ValidateC2BPayment' (returns SOAP_OK or error code)
        virtual int ValidateC2BPayment(_ns1__C2BPaymentValidationRequest *ns1__C2BPaymentValidationRequest, _ns1__C2BPaymentValidationResult &ns1__C2BPaymentValidationResult)
        { return this->ValidateC2BPayment(NULL, NULL, ns1__C2BPaymentValidationRequest, ns1__C2BPaymentValidationResult); }
        virtual int ValidateC2BPayment(const char *soap_endpoint, const char *soap_action, _ns1__C2BPaymentValidationRequest *ns1__C2BPaymentValidationRequest, _ns1__C2BPaymentValidationResult &ns1__C2BPaymentValidationResult);
        /// Web service operation 'ConfirmC2BPayment' (returns SOAP_OK or error code)
        virtual int ConfirmC2BPayment(_ns1__C2BPaymentConfirmationRequest *ns1__C2BPaymentConfirmationRequest, std::string &ns1__C2BPaymentConfirmationResult)
        { return this->ConfirmC2BPayment(NULL, NULL, ns1__C2BPaymentConfirmationRequest, ns1__C2BPaymentConfirmationResult); }
        virtual int ConfirmC2BPayment(const char *soap_endpoint, const char *soap_action, _ns1__C2BPaymentConfirmationRequest *ns1__C2BPaymentConfirmationRequest, std::string &ns1__C2BPaymentConfirmationResult);
    };
#endif
